language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE="en_US.UTF-8"
  - LANG="en_US.UTF-8"
  - WORKSPACE="KernLabel.xcworkspace"
  - SCHEME="KernLabel"
  - SDK="iphonesimulator10.0"
  - DESTINATION="platform=iOS Simulator,name=iPhone 6s"
before_install:
  - gem update --no-document cocoapods && pod repo update --silent
script:
  - set -o pipefail
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" test | xcpretty -c;
